package com.rombalabs.strutstospringtoolkit.jspconverter;

import com.rombalabs.strutstospringtoolkit.jspservices.PreProcessor;
import com.rombalabs.strutstospringtoolkit.jspservices.StrutsProcessor;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    private static final Logger logger = LogManager.getLogger();

    public static void main(String[] args) {

        boolean rewriteInPlace = false;
        if(args.length < 1)
        {
            logger.fatal("Please provide a file name as an argument.");
            return;
        }

        if(args.length == 2)
        {
            if (args[1].equals("--replace")) {
                rewriteInPlace = true;
            }
            else {
                logger.fatal("Invalid argument.");
                return;
            }
        }

        var preProcessor = new PreProcessor();
        var strutsProcessor = new StrutsProcessor();

        var outputFile = preProcessor.processFile(args[0], rewriteInPlace);
        strutsProcessor.processFile(outputFile, true);
    }
}
